-- AlterTable
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "trip_number" TEXT,
ADD COLUMN IF NOT EXISTS "cargo_description" TEXT,
ADD COLUMN IF NOT EXISTS "seal_number" TEXT,
ADD COLUMN IF NOT EXISTS "start_kms" INTEGER,
ADD COLUMN IF NOT EXISTS "km_out" INTEGER,
ADD COLUMN IF NOT EXISTS "km_in" INTEGER,
ADD COLUMN IF NOT EXISTS "run_km" INTEGER,
ADD COLUMN IF NOT EXISTS "eta" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "requested_date" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "requested_time" TEXT,
ADD COLUMN IF NOT EXISTS "arrival_at_loading" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "completed_loading" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "dispatch_from_loading" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "arrival_at_offloading" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "completed_unloading" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "remarks" TEXT,
ADD COLUMN IF NOT EXISTS "recipient_acknowledgment" TEXT;

